services:

  redis:
    container_name: redis 
    image: 'redis:7-alpine'
    user: "1000"
    command: redis-server --requirepass ${REDIS_PASSWORD:-verystrongpass}
    volumes:
      - 'redis-data:/data'
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  website:
    container_name: website
    build: .
    user: "1000"
    volumes:
      - '.:/app'
    depends_on:
      - redis
    ports:
      - '8000:5000'
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=0
      - SQLALCHEMY_DATABASE_URI=postgresql://enferno:${DB_PASSWORD:-verystrongpass}@postgres/enferno
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD:-verystrongpass}@redis:6379/2
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD:-verystrongpass}@redis:6379/3
      - SESSION_REDIS=redis://:${REDIS_PASSWORD:-verystrongpass}@redis:6379/1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    container_name: nginx
    restart: always
    image: 'nginx:alpine'
    user: "1000"
    ports:
      - '80:80'
    volumes:
      - './enferno/static/:/app/static/:ro'
      - './nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './nginx/enferno.conf:/etc/nginx/conf.d/default.conf:ro'
    tmpfs:
      - /tmp:exec,mode=1777
      - /var/run:mode=1777
      - /var/cache/nginx:mode=1777
    depends_on:
      - website
    healthcheck:
      test: [ "CMD", "service", "nginx", "status" ]

  celery:
    container_name: celery
    build: .
    user: "1000"
    command: celery -A enferno.tasks worker -l info
    volumes:
      - '.:/app'
    depends_on:
      - redis
    environment:
      - FLASK_APP=run.py
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD:-verystrongpass}@redis:6379/2
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD:-verystrongpass}@redis:6379/3

volumes:
  redis-data:
    driver: local
  enferno:
  nginx_tmp:
    driver: local
  nginx_run:
    driver: local
