site_name: Enferno Framework
site_description: A modern Python web framework built on Flask
site_url: https://enferno.readthedocs.io
repo_url: https://github.com/level09/enferno
repo_name: level09/enferno
edit_uri: edit/master/docs/

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Authentication: authentication.md
  - AI Features: ai-features.md
  - Deployment: deployment.md
  - Development: development.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search