[project]
name = "enferno"
version = "0.1.0"
description = "A modern Flask framework optimized for AI-assisted development workflows"
authors = [
    {name = "Level09", email = "hello@level09.com"}
]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.11"

dependencies = [
    "amqp==5.3.1",
    "babel==2.17.0",
    "bcrypt==4.3.0",
    "bleach==6.2.0",
    "blinker==1.9.0",
    "celery==5.5.3",
    "cffi==1.17.1",
    "click==8.2.1",
    "cryptography==45.0.5",
    "email-validator==2.2.0",
    "flask==3.1.1",
    "flask-caching==2.3.1",
    "flask-dance==7.1.0",
    "flask-debugtoolbar==0.16.0",
    "flask-login==0.6.3",
    "flask-mail==0.10.0",
    "flask-script==2.0.6",
    "flask-security-too==5.6.2",
    "flask-session==0.8.0",
    "flask-sqlalchemy==3.1.1",
    "flask-wtf==1.2.2",
    "itsdangerous==2.2.0",
    "jinja2==3.1.6",
    "kombu==5.5.4",
    "mako==1.3.10",
    "markupsafe==3.0.2",
    "argon2-cffi==23.1.0",
    "pillow==11.3.0",
    "psycopg2-binary==2.9.10",
    "pycparser==2.22",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.1.1",
    "python-editor==1.0.4",
    "pytz==2025.2",
    "qrcode==8.2",
    "redis==6.2.0",
    "six==1.17.0",
    "speaklater==1.3",
    "sqlalchemy==2.0.41",
    "uwsgi==2.0.30; sys_platform != 'win32'",
    "vine==5.1.0",
    "werkzeug==3.1.3",
    "webauthn==2.6.0",
    "wtforms==3.2.1",
    "orjson==3.10.18",
    "flask-babel==4.0.0",
    "rich==14.0.0",
    "setuptools>=80.9.0",
]

[project.optional-dependencies]
dev = [
    "black",
    "isort",
    "flake8",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "black",
    "isort", 
    "flake8",
]

[tool.black]
line-length = 88
target-version = ['py311']

[tool.isort]
profile = "black"
line_length = 88