site_name: Enferno Framework
pages:
- Home: index.md
- User Guide:
    - 'Installation': 'user-guide/installation.md'
- Developer Guide:
    - 'Libraries': 'developer-guide/libraries.md'
    
- About:
    - 'License': 'about/license.md'
    - 'Contributors': 'about/contributors.md'
    - 'Contributing': 'about/contributing.md'

theme: readthedocs
repo_url: https://github.com/level09/enferno/
site_author: Nidal Alhariri
